improve engrish
IsThicc/ThiccBot pull request #2
Opened 2021-09-17 19:24 UTC by RyderForReal

made the english thiccer by applying an advanced grammar filter.

In all seriousness, I improved the English in the README a bit. Feel free to let me know if you'd like any changes, either via a comment on this PR or via Discord.

2021-09-17 19:28 UTC, RyderForReal commented
Question - would you prefer "Feel free to fork this repo and make any edits you think would be beneficial. An IsThicc staff member will review your pull request and approve or deny it." or
"Feel free to fork this repo and make any edits you think would be beneficial. After you create a pull request, an IsThicc staff member will review it."?

I'm personally more of a fan of the second version.

2021-09-17 19:53 UTC, Mrmagicpie requested changes
Everything looks good, but since I'm bad at git, can you revert that one paragraph? Thanks for the pr, Ryder!

2021-09-17 19:53 UTC, Mrmagicpie commented on README.md
> +We reserve the right to reject any pull request or edits without reason or warning. When editing any IsThicc source code, you waive all rights over the code you contribute. Any attempt to claim the c
We generally do not allow the editing of our legal information. Everything else looks good in this commit but this gives a different context to this paragraph.

2021-09-18 17:12 UTC, RyderForReal commented
version 1, submitting second pr with alternative legal stuff

2021-09-18 18:19 UTC, Mrmagicpie approved these changes
Looks good. Thank you for your contribution.

2021-09-18 18:19 UTC, merged